Added onnxslim command test. input shapes/FP32 to FP16
inisis/OnnxSlim pull request #51
Opened 2024-11-26 07:58 UTC by whyb

Added OnnxSlim command test.

* Test the basic functionality of the slim function
* Test the modification of input shapes.
* Test the conversion of an ONNX model from FP32 to FP16 precision.
* Test the conversion of an ONNX model from FP16 to FP32 precision.

2024-11-26 08:53 UTC, inisis commented
Good Job!

2024-11-27 02:18 UTC, whyb commented
@inisis 

Could not merge this pr to main branch, Because CI test failed.

Test command:
```shell
onnxslim --input-shapes input:1,3,224,224 "/data/modelzoo/resnet18/resnet18.onnx" "/tmp/tmpj1kh/resnet18_fp16.onnx“
```

Failed message:
```shell
 =========================== short test summary info ============================
FAILED tests/test_onnxslim.py::TestFunctional::test_input_shape_modification - assert 2 == 0
 +  where 2 = CompletedProcess(args='onnxslim --input-shapes input:1,3,224,224 "/data/modelzoo/resnet18/resnet18.onnx" "/tmp/tmpj1kh...-v]\n                input_model [output_model]\nonnxslim: error: the following arguments are required: input_model\n').returncode
FAILED tests/test_onnxslim.py::TestFunctional::test_fp322fp16_conversion - FileNotFoundError: [Errno 2] No such file or directory: '/tmp/tmpgmnl41ah/resnet18_fp16.onnx'
================== 2 failed, 5 passed, 107 warnings in 10.90s ==================
```

2024-11-27 02:34 UTC, inisis requested changes

2024-11-27 02:34 UTC, inisis commented on tests/test_onnxslim.py
> +            command = f'onnxslim {arg_str} "{in_model_path}" "{out_model_path}"'
I think the *arg_str* should be placed after *input_model* and *output_model*

2024-11-27 04:44 UTC, inisis approved these changes

2024-11-28 00:28 UTC, inisis approved these changes

2024-11-28 00:28 UTC, merged

2024-11-28 00:29 UTC, inisis commented
@whyb Thanks for your contributions!